server:
  servlet:
    context-path: /todo/api/v1
    
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        # Disable feature detection by this undocumented parameter for clob() impl
        temp:
          use_jdbc_metadata_defaults: false
